In [1]:
#About slicing
import numpy as np
list1 = [1,2,3,4,5,6,7,8]
list2 = list1
check = list1[::] 
check.pop()
# list2.pop() to check if slicing copies and by common sense it will deep copy
list1


[1, 2, 3, 4, 5, 6, 7, 8]

In [2]:
a1 = np.arange(10).reshape(2,5)
print(a1)
a1[:, :2]
#slicing 2d arrays 



[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[0, 1],
       [5, 6]])

In [3]:
a3 = np.arange(1,28).reshape(3,3,3)
#will try to access/get 1st 2d arr and 3rd 2d arr's first and last column
print(a3)# to check 
a3[::2,:, ::2 ]#done

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([[[ 1,  3],
        [ 4,  6],
        [ 7,  9]],

       [[19, 21],
        [22, 24],
        [25, 27]]])

In [20]:
#Fancy Indexing
#on slicing we can access the elements by certain patterns but if we want to access element and there is no pattern then we use fancy indexing
print(a3)
# print(a3[[0,1],[[0],[2]],[0,2]]) trial only failed but discovered something new 
a3[[0,0,0,0,1,1],[0,0,2,2,2,2],[0,2,0,2,0,2]] # i think this is not the way but get's the job done


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([ 1,  3,  7,  9, 16, 18])

In [ ]:
a3<20#basically returns a boolean 
print(a3<20)
a3[(a3<20) & (a3<30)]
#this is basically boolean indexing


[[[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True False False]
  [False False False]
  [False False False]]]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])