In [2]:
#About slicing
import numpy as np
list1 = [1,2,3,4,5,6,7,8]
list2 = list1
check = list1[::] 
check.pop()
# list2.pop() to check if slicing copies and by common sense it will deep copy
list1


[1, 2, 3, 4, 5, 6, 7, 8]

In [3]:
a1 = np.arange(10).reshape(2,5)
print(a1)
a1[:, :2]
#slicing 2d arrays 



[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[0, 1],
       [5, 6]])

In [4]:
a3 = np.arange(1,28).reshape(3,3,3)
#will try to access/get 1st 2d arr and 3rd 2d arr's first and last column
print(a3)# to check 
a3[::2,:, ::2 ]#done

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([[[ 1,  3],
        [ 4,  6],
        [ 7,  9]],

       [[19, 21],
        [22, 24],
        [25, 27]]])

In [5]:
#Fancy Indexing
#on slicing we can access the elements by certain patterns but if we want to access element and there is no pattern then we use fancy indexing
print(a3)
# print(a3[[0,1],[[0],[2]],[0,2]]) trial only failed but discovered something new 
a3[[0,0,0,0,1,1],[0,0,2,2,2,2],[0,2,0,2,0,2]] # i think this is not the way but get's the job done


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([ 1,  3,  7,  9, 16, 18])

In [6]:
a3<20#basically returns a boolean 
print(a3<20)
a3[(a3<20) & (a3<30)] #& is bit wise operator that's why it's working here 'and' will not work here
#this is basically boolean indexing


[[[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True False False]
  [False False False]
  [False False False]]]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [11]:
#Broadcasting rules
# basically if there is 1 on either row or column you can increase it to match with the other array to make both same dimension and perform mathematical operationis
a1 = np.arange(9).reshape(3,3)
a2 = np.arange(3)
print(f'a2 = {a2}')
a1+a2 #a2 shape is only(,3) while a1 shape is (3,3) so for addition both array's dimension must be same now look at magic of broadcasting
#basically if the array is only 1 dimension then first make it 2d by putting 1 in front i.e (1,3) then make it same as the another array that is 3
#if the array is already 2d and doesn't include  1 on either row or column and the shape doesnt match with another array then error will show up



a2 = [0 1 2]


array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [ ]:
#sigmoid basically makes any value in the range of 0 and 1 negative values are close to 0 then positive values are close to 1
# e/exp is just a constant like pi its value is 2.71828......
#basically some understanding of e and pi which is actually cool like how it was formed and why its value is that
print(np.exp(1),np.exp(2)) #basically first argument is it's power exp(2) = exp square
#check
a1 = np.arange(1,10)
1/a1
def sigmoid(arr):
	return 1/1-(np.exp(-arr))
sigmoid(a1)

2.718281828459045 7.38905609893065


array([0.63212056, 0.86466472, 0.95021293, 0.98168436, 0.99326205,
       0.99752125, 0.99908812, 0.99966454, 0.99987659])

In [25]:
#The slope of a curve at a particular point. is derivative
#Mean Squarred error = actual value - predected value of all the iterations and squarring them so that they don't cancel each other out and adding all and divided all by n which is basically mean
def meanSquarredError(actualArr, predArr):
	return np.mean((actualArr-predArr)**2)
a2 = np.arange(11,20)
print(meanSquarredError(a1,a2))

100.0
